<!DOCTYPE html>
<html lang="ru">

<head>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Hello World</title>

  <link href="@styles/style.scss" rel="stylesheet">
</head>

<body>
  <div class="wrapper">
    <header>
      <label for="open-dialog" class="button">Open pop-up button</label>
      <input type="checkbox" name="open-dialog" id="open-dialog">
      <dialog>
        Pop-up
        <form method="dialog">
          <label for="open-dialog" class="button">x</label>
        </form>
      </dialog>
    </header>